import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ali Yaghuti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my site!
        </h1>
        <p>Under Construction...</p>
      </main>

      <footer className={styles.footer}>
      <p className="text-center">&copy; Ali yaghuti 2015 - {new Date().getFullYear()}</p>
      </footer>
    </div>
  )
}
